import EditableCell from "../components/Table/EditableCell";

const columns = [
    {
     accessorKey: "Row_ID",
     header: "Id",
     size: 225,
     cell: EditableCell,
    },
    {
     accessorKey: "Product_Name",
     header: "Product Name",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
     filterFn: "includesString",
   },
   {
     accessorKey: "State",
     header: "State",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
     filterFn: "includesString",
   },
   {
     accessorKey: "Profit",
     header: "Profit",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Product_ID",
     header: "Product ID",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
     filterFn: "includesString",
   },
    {
     accessorKey: "Order_ID",
     header: "Order Id",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
     filterFn: "includesString",
   },
   {
     accessorKey: "Order_Date",
     header: "Order Date",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Ship_Date",
     header: "Ship Date",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Ship_Mode",
     header: "Ship Mode",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Customer_ID",
     header: "Customer ID",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Customer_Name",
     header: "Customer Name",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Segment",
     header: "Segment",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "City",
     header: "City",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   
   {
     accessorKey: "Region",
     header: "Region",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Category",
     header: "Category",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Sub-Category",
     header: "Sub-Category",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Sales",
     header: "Sales",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Quantity",
     header: "Quantity",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   {
     accessorKey: "Discount",
     header: "Discount",
     size: 225,
     cell: EditableCell,
     enableColumnFilter: true,
   },
   
 ];

    export default columns;